version: "3.7"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8888:8888"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: dev
      SECRET_KEY: secretKey
      LOG_FORMAT: dev
      LOG_DIR: /logs
      ORIGIN: "http://localhost:3000"
      CREDENTIALS: "true"

    restart: "unless-stopped"
    networks:
      - backend
    links:
      - pg
    depends_on:
      - pg
  pg:
    container_name: pg
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
